/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.action'

export { $nsid }

/** An action verb defining the kind of flow and its behavior. */
type Main = {
  $type: 'org.openassociation.action'

  /**
   * The canonical identifier for this action type
   */
  actionId:
    | 'accept'
    | 'cite'
    | 'combine'
    | 'consume'
    | 'copy'
    | 'deliverService'
    | 'dropoff'
    | 'lower'
    | 'modify'
    | 'move'
    | 'pickup'
    | 'produce'
    | 'raise'
    | 'separate'
    | 'transfer'
    | 'transferAllRights'
    | 'transferCustody'
    | 'use'
    | 'work'
    | l.UnknownString

  /**
   * The display label defined for the network for the unit of measure, overrides om.
   */
  label: string

  /**
   * Denotes if a process input or output, or not applicable to a process.
   */
  inputOutput?:
    | 'input'
    | 'notApplicable'
    | 'output'
    | 'outputInput'
    | l.UnknownString

  /**
   * The action that usually affects the same resource as a complement in the same flow.
   */
  pairsWith?: string

  /**
   * The action can create an economic resource.
   */
  createResource?: 'notApplicable' | 'optional' | 'optionalTo' | l.UnknownString

  /**
   * The event quantity applicable is resource quantity, effort quantity, or both.
   */
  eventQuantity?: 'both' | 'effort' | 'resource' | l.UnknownString

  /**
   * The increment and/or decrement effect the action will have on the accounting quantity of an inventoried resource.
   */
  accountingEffect?:
    | 'decrement'
    | 'decrementIncrement'
    | 'increment'
    | 'incrementTo'
    | l.UnknownString

  /**
   * The increment and/or decrement effect the action will have on the onhand quantity of an inventoried resource.
   */
  onhandEffect?:
    | 'decrement'
    | 'decrementIncrement'
    | 'increment'
    | 'incrementTo'
    | l.UnknownString

  /**
   * This action can update the current location of an inventoried resource.
   */
  locationEffect?:
    | 'new'
    | 'notApplicable'
    | 'update'
    | 'updateTo'
    | l.UnknownString

  /**
   * The contained in resource should be updated or removed.
   */
  containedEffect?:
    | 'notApplicable'
    | 'remove'
    | 'update'
    | 'updateTo'
    | l.UnknownString

  /**
   * The primaryAccountable should be updated to the event receiver, or not.
   */
  accountableEffect?: 'new' | 'updateTo' | l.UnknownString

  /**
   * The stage of the inventoried resource should be updated, or not.
   */
  stageEffect?: 'update' | l.UnknownString

  /**
   * The state of the from or to inventoried resource should be updated, or not.
   */
  stateEffect?: 'update' | 'updateTo' | l.UnknownString
}

export type { Main }

/** An action verb defining the kind of flow and its behavior. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    actionId: l.string(),
    label: l.string(),
    inputOutput: l.optional(l.string()),
    pairsWith: l.optional(l.string()),
    createResource: l.optional(l.string()),
    eventQuantity: l.optional(l.string()),
    accountingEffect: l.optional(l.string()),
    onhandEffect: l.optional(l.string()),
    locationEffect: l.optional(l.string()),
    containedEffect: l.optional(l.string()),
    accountableEffect: l.optional(l.string()),
    stageEffect: l.optional(l.string()),
    stateEffect: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
