/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as OpenassociationDefs from './defs.defs.js'

const $nsid = 'org.openassociation.claim'

export { $nsid }

/** A claim for a future economic event(s) in reciprocity for an economic event that already occurred. */
type Main = {
  $type: 'org.openassociation.claim'

  /**
   * Defines the kind of flow, such as consume, produce, work, transfer, etc.
   */
  action: l.AtUriString

  /**
   * The economic agent by whom the intended, committed, or actual economic event is initiated.
   */
  provider?: l.DidString

  /**
   * The economic agent whom the intended, committed, or actual economic event is for.
   */
  receiver?: l.DidString

  /**
   * References an economic event that implied the claim, often based on a prior agreement.
   */
  triggeredBy?: l.AtUriString

  /**
   * The date, and time if desired, something is expected to be complete.
   */
  due?: l.DatetimeString

  /**
   * The amount and unit of the economic resource counted or inventoried.
   */
  resourceQuantity?: OpenassociationDefs.Measure

  /**
   * The amount and unit of the work or use or citation effort-based action. This is often expressed with a time unit, but also could be cycle counts or other measures of effort or usefulness.
   */
  effortQuantity?: OpenassociationDefs.Measure

  /**
   * The date, and time if desired, the information was agreed to or recorded.
   */
  created?: l.DatetimeString

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * The commitment or intent or process is complete or not.  This is irrespective of if the original goal has been met, and indicates simply that no more will be done.  Default false.
   */
  finished?: boolean

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.
   */
  resourceClassifiedAs?: string[]

  /**
   * The lowest level resource specification or definition of an existing or potential economic resource, whether one will ever be instantiated or not.
   */
  resourceConformsTo?: l.AtUriString
}

export type { Main }

/** A claim for a future economic event(s) in reciprocity for an economic event that already occurred. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    action: l.string({ format: 'at-uri' }),
    provider: l.optional(l.string({ format: 'did' })),
    receiver: l.optional(l.string({ format: 'did' })),
    triggeredBy: l.optional(l.string({ format: 'at-uri' })),
    due: l.optional(l.string({ format: 'datetime' })),
    resourceQuantity: l.optional(
      l.ref<OpenassociationDefs.Measure>(
        (() => OpenassociationDefs.measure) as any,
      ),
    ),
    effortQuantity: l.optional(
      l.ref<OpenassociationDefs.Measure>(
        (() => OpenassociationDefs.measure) as any,
      ),
    ),
    created: l.optional(l.string({ format: 'datetime' })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    finished: l.optional(l.boolean()),
    resourceClassifiedAs: l.optional(l.array(l.string())),
    resourceConformsTo: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
