/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.createResourceSpecification'

export { $nsid }

/** Create or update a resourceSpecification record. Include `uri` in the body to update an existing record. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.payload('application/json'),
  l.payload('application/json'),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Input = l.InferMethodInput<typeof main>
export type InputBody = l.InferMethodInputBody<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
