/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.defs'

export { $nsid }

/** A quantity expressed as a numeric value with a unit of measure. AT Protocol does not support floats, so the value is represented as numerator/denominator integers. */
type Measure = {
  $type?: 'org.openassociation.defs#measure'

  /**
   * The numeric value (numerator).
   */
  hasNumericalValue: number

  /**
   * The denominator for fractional values. Default 1 if omitted.
   */
  hasDenominator?: number

  /**
   * Reference to a Unit record.
   */
  hasUnit?: l.AtUriString
}

export type { Measure }

/** A quantity expressed as a numeric value with a unit of measure. AT Protocol does not support floats, so the value is represented as numerator/denominator integers. */
const measure = l.typedObject<Measure>(
  $nsid,
  'measure',
  l.object({
    hasNumericalValue: l.integer(),
    hasDenominator: l.optional(l.integer()),
    hasUnit: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { measure }
