/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as OpenassociationDefs from './defs.defs.js'

const $nsid = 'org.openassociation.economicEvent'

export { $nsid }

/** An observed economic flow, which could reflect creation or a change in the quantity, location, accountability and/or responsibility, of an economic resource, whether material or not. */
type Main = {
  $type: 'org.openassociation.economicEvent'

  /**
   * Defines the kind of flow, such as consume, produce, work, transfer, etc.
   */
  action: l.AtUriString

  /**
   * Relates an input flow to its process.
   */
  inputOf?: l.AtUriString

  /**
   * Relates an output flow to its process.
   */
  outputOf?: l.AtUriString

  /**
   * Economic resource involved in the flow.
   */
  resourceInventoriedAs?: l.AtUriString

  /**
   * Additional economic resource on the economic event when needed by the receiver. Used when a transfer or move, or sometimes other actions, requires explicitly identifying an economic resource by the receiver, which is identified differently by the sender.
   */
  toResourceInventoriedAs?: l.AtUriString

  /**
   * The economic agent by whom the intended, committed, or actual economic event is initiated.
   */
  provider?: l.DidString

  /**
   * The economic agent whom the intended, committed, or actual economic event is for.
   */
  receiver?: l.DidString

  /**
   * Used when an event was entered incorrectly and needs to be backed out or corrected. (The initial event cannot be changed.)
   */
  corrects?: l.AtUriString

  /**
   * The claim(s) settled fully or partially by the economic event.
   */
  settles?: l.AtUriString[]

  /**
   * The planned or actual beginning date, and time if desired, of a flow or process.
   */
  hasBeginning?: l.DatetimeString

  /**
   * The planned or actual ending date, and time if desired, of a flow or process.
   */
  hasEnd?: l.DatetimeString

  /**
   * The planned or actual date, and time if desired, of a flow; can be used instead of hasBeginning and hasEnd, if so, hasBeginning and hasEnd should be able to return this value.
   */
  hasPointInTime?: l.DatetimeString

  /**
   * The amount and unit of the economic resource counted or inventoried.
   */
  resourceQuantity?: OpenassociationDefs.Measure

  /**
   * The amount and unit of the work or use or citation effort-based action. This is often expressed with a time unit, but also could be cycle counts or other measures of effort or usefulness.
   */
  effortQuantity?: OpenassociationDefs.Measure

  /**
   * The date, and time if desired, the information was agreed to or recorded.
   */
  created?: l.DatetimeString

  /**
   * The new location of the receiver resource.
   */
  toLocation?: l.AtUriString

  /**
   * The uri to an image relevant to the entity, such as a logo, avatar, photo, diagram, etc.
   */
  image?: l.UriString

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * The commitment(s) fulfilled completely or partially by an economic event.
   */
  fulfills?: l.AtUriString[]

  /**
   * The intent(s) satisfied fully or partially by an economic event or commitment.
   */
  satisfies?: l.AtUriString[]

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.
   */
  resourceClassifiedAs?: string[]

  /**
   * The lowest level resource specification or definition of an existing or potential economic resource, whether one will ever be instantiated or not.
   */
  resourceConformsTo?: l.AtUriString

  /**
   * The required state of the desired input economic resource, after coming out of a test or review process.
   */
  state?: string

  /**
   * This non-reciprocal economic event occurs as part of this agreement.
   */
  realizationOf?: l.AtUriString

  /**
   * This reciprocal economic event occurs as part of this agreement.
   */
  reciprocalRealizationOf?: l.AtUriString
}

export type { Main }

/** An observed economic flow, which could reflect creation or a change in the quantity, location, accountability and/or responsibility, of an economic resource, whether material or not. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    action: l.string({ format: 'at-uri' }),
    inputOf: l.optional(l.string({ format: 'at-uri' })),
    outputOf: l.optional(l.string({ format: 'at-uri' })),
    resourceInventoriedAs: l.optional(l.string({ format: 'at-uri' })),
    toResourceInventoriedAs: l.optional(l.string({ format: 'at-uri' })),
    provider: l.optional(l.string({ format: 'did' })),
    receiver: l.optional(l.string({ format: 'did' })),
    corrects: l.optional(l.string({ format: 'at-uri' })),
    settles: l.optional(l.array(l.string({ format: 'at-uri' }))),
    hasBeginning: l.optional(l.string({ format: 'datetime' })),
    hasEnd: l.optional(l.string({ format: 'datetime' })),
    hasPointInTime: l.optional(l.string({ format: 'datetime' })),
    resourceQuantity: l.optional(
      l.ref<OpenassociationDefs.Measure>(
        (() => OpenassociationDefs.measure) as any,
      ),
    ),
    effortQuantity: l.optional(
      l.ref<OpenassociationDefs.Measure>(
        (() => OpenassociationDefs.measure) as any,
      ),
    ),
    created: l.optional(l.string({ format: 'datetime' })),
    toLocation: l.optional(l.string({ format: 'at-uri' })),
    image: l.optional(l.string({ format: 'uri' })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    fulfills: l.optional(l.array(l.string({ format: 'at-uri' }))),
    satisfies: l.optional(l.array(l.string({ format: 'at-uri' }))),
    resourceClassifiedAs: l.optional(l.array(l.string())),
    resourceConformsTo: l.optional(l.string({ format: 'at-uri' })),
    state: l.optional(l.string()),
    realizationOf: l.optional(l.string({ format: 'at-uri' })),
    reciprocalRealizationOf: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
