/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.listActions'

export { $nsid }

/** List actions. Filterable by: actionId, inputOutput, createResource, eventQuantity, accountingEffect, onhandEffect, locationEffect, containedEffect, accountableEffect, stageEffect, stateEffect. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    actionId: l.optional(l.string()),
    inputOutput: l.optional(l.string()),
    createResource: l.optional(l.string()),
    eventQuantity: l.optional(l.string()),
    accountingEffect: l.optional(l.string()),
    onhandEffect: l.optional(l.string()),
    locationEffect: l.optional(l.string()),
    containedEffect: l.optional(l.string()),
    accountableEffect: l.optional(l.string()),
    stageEffect: l.optional(l.string()),
    stateEffect: l.optional(l.string()),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.payload('application/json'),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
