/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.listAgreements'

export { $nsid }

/** List agreements. Filterable by: stipulates, stipulatesReciprocal, realizes, realizesReciprocal, bundledIn. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    stipulates: l.optional(l.string({ format: 'at-uri' })),
    stipulatesReciprocal: l.optional(l.string({ format: 'at-uri' })),
    realizes: l.optional(l.string({ format: 'at-uri' })),
    realizesReciprocal: l.optional(l.string({ format: 'at-uri' })),
    bundledIn: l.optional(l.string({ format: 'at-uri' })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.payload('application/json'),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
