/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.listProposals'

export { $nsid }

/** List proposals. Filterable by: unitBased, purpose, publishes, reciprocal, proposedTo, listedIn. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    unitBased: l.optional(l.boolean()),
    purpose: l.optional(l.string()),
    publishes: l.optional(l.string({ format: 'at-uri' })),
    reciprocal: l.optional(l.string({ format: 'at-uri' })),
    proposedTo: l.optional(l.string({ format: 'did' })),
    listedIn: l.optional(l.string({ format: 'at-uri' })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.payload('application/json'),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
