/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as OpenassociationDefs from './defs.defs.js'

const $nsid = 'org.openassociation.recipeProcess'

export { $nsid }

/** Specifies a process in a recipe for use in planning from recipe. */
type Main = {
  $type: 'org.openassociation.recipeProcess'

  /**
   * All the inputs of a recipe process.
   */
  hasRecipeInput?: l.AtUriString[]

  /**
   * All the outputs of a recipe process.
   */
  hasRecipeOutput?: l.AtUriString[]

  /**
   * The temporal extent of the process.
   */
  hasDuration?: OpenassociationDefs.Measure

  /**
   * The uri to an image relevant to the entity, such as a logo, avatar, photo, diagram, etc.
   */
  image?: l.UriString

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.
   */
  processClassifiedAs?: string[]

  /**
   * The standard specification or definition of a type of process.
   */
  processConformsTo?: l.AtUriString
}

export type { Main }

/** Specifies a process in a recipe for use in planning from recipe. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    hasRecipeInput: l.optional(l.array(l.string({ format: 'at-uri' }))),
    hasRecipeOutput: l.optional(l.array(l.string({ format: 'at-uri' }))),
    hasDuration: l.optional(
      l.ref<OpenassociationDefs.Measure>(
        (() => OpenassociationDefs.measure) as any,
      ),
    ),
    image: l.optional(l.string({ format: 'uri' })),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    processClassifiedAs: l.optional(l.array(l.string())),
    processConformsTo: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
