/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.spatialThing'

export { $nsid }

/** Data that locates something relative to the Earth, usually a somewhat fixed location. */
type Main = {
  $type: 'org.openassociation.spatialThing'

  /**
   * The WGS84 longitude of a spatial thing (decimal degrees).
   */
  long?: string

  /**
   * The WGS84 latitude of a spatial thing (decimal degrees).
   */
  lat?: string

  /**
   * The WGS84 altitude of a spatial thing (decimal meters above the local reference ellipsoid)
   */
  alt?: string

  /**
   * A textual address that can be mapped using mapping software.
   */
  mappableAddress?: string

  /**
   * A spatial geometry of any complexity and tooling supported by geosparql.
   */
  hasDetailedGeometry?: string

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string
}

export type { Main }

/** Data that locates something relative to the Earth, usually a somewhat fixed location. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    long: l.optional(l.string()),
    lat: l.optional(l.string()),
    alt: l.optional(l.string()),
    mappableAddress: l.optional(l.string()),
    hasDetailedGeometry: l.optional(l.string()),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
