##
#
# Agent <> Agreement query API
#
# Provides information about the agents involved in agreements.
#
# @package  vf-graphql
# @author   pospi <pospi@spadgos.com>
# @since    2020-02-12
#
##

type Agreement {
  involvedAgents(first: Int, after: String, last: Int, before: String): AgentConnection
}
