##
#
# Query filter parameters for Agent <> Observation relationships
#
# :TODO: decide on final set
# @see https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/90

# @package  ValueFlows GraphQL
# @since    2021-12-13
#
##

"Query parameters for reading `EconomicEvent`s related to an `Agent`"
input AgentEventFilterParams {
  searchString: String
  action: ID
  startDate: DateTime
  endDate: DateTime
}

"Query parameters for reading `EconomicResource`s related to an `Agent`"
input AgentResourceFilterParams {
  searchString: String
  resourceClassification: URI
  page: Int
}

"Query parameters for reading `Process`es related to an `Agent`"
input AgentProcessFilterParams {
  searchString: String
  finished: Boolean
}

interface Agent {
  economicEvents(filter: AgentEventFilterParams): EconomicEventConnection
  inventoriedEconomicResources(filter: AgentResourceFilterParams): EconomicResourceConnection
  processes(filter: AgentProcessFilterParams): ProcessConnection
}

type Person implements Agent {
  economicEvents(filter: AgentEventFilterParams): EconomicEventConnection
  inventoriedEconomicResources(filter: AgentResourceFilterParams): EconomicResourceConnection
  processes(filter: AgentProcessFilterParams): ProcessConnection
}

type Organization implements Agent {
  economicEvents(filter: AgentEventFilterParams): EconomicEventConnection
  inventoriedEconomicResources(filter: AgentResourceFilterParams): EconomicResourceConnection
  processes(filter: AgentProcessFilterParams): ProcessConnection
}
