##
#
# Agent <> Observation API
#
# Queries & related to observation-level data exposed within an agent context,
# and identifiers linking Agents to observation record types.
#
# @package  vf-graphql
# @since    2020-02-11
#
##

type EconomicEvent {
  "The economic agent from whom the actual economic event is initiated."
  provider: Agent!

  "The economic agent whom the actual economic event is for."
  receiver: Agent!

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AccountingScope!]
}

type EconomicResource {
  "The agent currently with primary rights and responsibilites for the economic resource. It is the agent that is associated with the accountingQuantity of the economic resource."
  primaryAccountable: Agent
}

input EconomicEventCreateParams {
  "(`Agent`) The economic agent from whom the actual economic event is initiated."
  provider: ID!

  "(`Agent`) The economic agent whom the actual economic event is for."
  receiver: ID!
}

interface Agent {
  economicEvents(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsAsProvider(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsAsReceiver(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsInScope(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  inventoriedEconomicResources(first: Int, after: String, last: Int, before: String): EconomicResourceConnection
}

type Person implements Agent {
  economicEvents(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsAsProvider(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsAsReceiver(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsInScope(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  inventoriedEconomicResources(first: Int, after: String, last: Int, before: String): EconomicResourceConnection
}

type Organization implements Agent {
  economicEvents(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsAsProvider(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsAsReceiver(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  economicEventsInScope(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  inventoriedEconomicResources(first: Int, after: String, last: Int, before: String): EconomicResourceConnection
}
