##
# Agent <> Process API
#
# Defines bi-directional relationships that can exist, and be queried.
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type Process {
  involvedAgents(first: Int, after: String, last: Int, before: String): AgentConnection
  workingAgents(first: Int, after: String, last: Int, before: String): AgentConnection

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AccountingScope!]
}

##
#  API call input and output types
##

input ProcessCreateParams {
  "(`AccountingScope`) Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [ID!]
}

input ProcessUpdateParams {
  "(`AccountingScope`) Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [ID!]
}

interface Agent {
  processes(
    first: Int
    after: String
    last: Int
    before: String
  ): ProcessConnection
}

type Person implements Agent {
  processes(
    first: Int
    after: String
    last: Int
    before: String
  ): ProcessConnection
}

type Organization implements Agent {
  processes(
    first: Int
    after: String
    last: Int
    before: String
  ): ProcessConnection
}
