##
#
# Agent <> Commitment API
#
# Queries related to Commitment data exposed within an agent context,
# and identifiers linking Agents to Commitment record types.
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type Commitment {
  "The economic agent from whom the commitment is initiated."
  provider: Agent!

  "The economic agent whom the commitment is for."
  receiver: Agent!

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AccountingScope!]

  ##############################################################################
  # inverse relationships and queries

  involvedAgents: [Agent!]
}

input CommitmentCreateParams {
  "(`Agent`) The economic agent from whom the commitment is initiated."
  provider: ID!

  "(`Agent`) The economic agent whom the commitment is for."
  receiver: ID!

  "(`AccountingScope`) Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [ID!]
}

input CommitmentUpdateParams {
  "(`Agent`) The economic agent from whom the commitment is initiated."
  provider: ID

  "(`Agent`) The economic agent whom the commitment is for."
  receiver: ID

  "(`AccountingScope`) Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [ID!]
}

interface Agent {
  commitments(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsAsProvider(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsAsReceiver(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsInScope(first: Int, after: String, last: Int, before: String): CommitmentConnection
}

type Person implements Agent {
  commitments(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsAsProvider(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsAsReceiver(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsInScope(first: Int, after: String, last: Int, before: String): CommitmentConnection
}

type Organization implements Agent {
  commitments(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsAsProvider(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsAsReceiver(first: Int, after: String, last: Int, before: String): CommitmentConnection
  commitmentsInScope(first: Int, after: String, last: Int, before: String): CommitmentConnection
}
