##
#
# Query filter parameters for Agent <> Proposal relationships
#
# :TODO: decide on final set
# @see https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/90

# @package  vf-graphql
# @since    2021-12-13
#
##

"Query parameters for reading `Proposal`s related to an `Agent`"
input agentProposalSearchParams {
  searchString: String
}

interface Agent {
  proposals(filter: agentProposalSearchParams): ProposalConnection
}

type Person implements Agent {
  proposals(filter: agentProposalSearchParams): ProposalConnection
}

type Organization implements Agent {
  proposals(filter: agentProposalSearchParams): ProposalConnection
}
