##
#
# Query filter parameters for Agent <> Plan relationships
#
# :TODO: decide on final set
# @see https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/90

# @package  vf-graphql
# @since    2020-02-11
#
##

"Query parameters for reading `Plan`s related to an `Agent`"
input AgentPlanFilterParams {
  searchString: String
  finished: Boolean
}

interface Agent {
  plans(filter: AgentPlanFilterParams): PlanConnection
}

type Person implements Agent {
  plans(filter: AgentPlanFilterParams): PlanConnection
}

type Organization implements Agent {
  plans(filter: AgentPlanFilterParams): PlanConnection
}
