##
#
# Commitment <> ProcessSpecification query edges
#
# @package  vf-graphql
# @since    2022-06-16
#
##

type Commitment {
  "References the ProcessSpecification of the last process the economic resource went through. Stage is used when the last process is important for finding proper resources, such as where the publishing process wants only documents that have gone through the editing process."
  stage: ProcessSpecification
}

type CommitmentCreateParams {
  "The process stage of the commitment."
  stage: URI
}

type CommitmentUpdateParams {
  "The process stage of the commitment."
  stage: URI
}

type ProcessSpecification {
  commitmentsRequiringStage(first: Int, after: String, last: Int, before: String): CommitmentConnection
}
