type EconomicEvent {
  revision(revisionId: ID!): EconomicEvent
  meta: RecordMeta!
}

type EconomicResource {
  revision(revisionId: ID!): EconomicResource
  meta: RecordMeta!
}

type ProductBatch {
  revision(revisionId: ID!): ProductBatch
  meta: RecordMeta!
}

type Process {
  revision(revisionId: ID!): Process
  meta: RecordMeta!
}
