##
#
# Intent <> Satisfaction API
#
# Extend Intents with Satisfactions
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type Intent {
  ##############################################################################
  # inverse relationships and queries

  satisfiedBy: [Satisfaction!]
}

# Note the inverse relationship is not also here, it is in satisfaction.gql
# since satisfaction does basically nothing without Intent.
