##
#
# Intent <> Proposal indexes
#
# Enables traversing Intent links into related Proposal modules.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type Intent {
  publishedIn: [ProposedIntent!]
}

type Proposal {
  primaryIntents: [Intent!]
  reciprocalIntents: [Intent!]
}

type ProposedIntent {
  "The intent which is part of this published proposal."
  publishes: Intent!
}
