input IntentFilterParams {
  searchString: String
  providerId: [ID!]
  receiverId: [ID!]
  resourceClassifiedAs: [URI!]
  resourceConformsTo: [ID!]
  finished: Boolean
  action: [ID!]
  startDate: DateTime
  endDate: DateTime
  inScopeOf: [ID!]
}

type Query {
  intents(filter: IntentFilterParams): IntentConnection!
}
