##
#
# Intent <> Geolocation API
#
# Augments records of Intent events with geospatial information.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type Intent {
  "The place where an intent would occur. Usually mappable."
  atLocation: SpatialThing
}

type SpatialThing {
  intents: [Intent!]
}

input IntentCreateParams {
  "(`SpatialThing`) The place where an intent occurs. Usually mappable."
  atLocation: ID
}

input IntentUpdateParams {
  "(`SpatialThing`) The place where an intent occurs. Usually mappable."
  atLocation: ID
}
