##
#
# Intent <> Observation API
#
# Extend Intents with actual Economic Resources from Observation
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type Intent {
  "When a specific `EconomicResource` is known which can service the `Intent`, this defines that resource."
  resourceInventoriedAs: EconomicResource
}

type EconomicResource {
  intents(first: Int, after: String, last: Int, before: String): IntentConnection
}

##
# API input and output types
##

input IntentCreateParams {
  "(`EconomicResource`) When a specific `EconomicResource` is known which can service the `Intent`, this defines that resource."
  resourceInventoriedAs: ID
}

input IntentUpdateParams {
  "(`EconomicResource`) When a specific `EconomicResource` is known which can service the `Intent`, this defines that resource."
  resourceInventoriedAs: ID
}
