##
#
# Query filter parameters for the Observation module
#
# :TODO: decide on final set, and align with agent.observation.filtering params
# @see https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/90
#
# @package  ValueFlows GraphQL
# @since    2021-12-13
#
##

input EconomicEventFilterParams {
  searchString: String
  providerId: [ID!]
  receiverId: [ID!]
  resourceClassifiedAs: [URI!]
  action: [ID!]
  startDate: DateTime
  endDate: DateTime
}

type Query {
  economicEvents(filter: EconomicEventFilterParams): EconomicEventConnection!
}
