##
#
# Observation <> Fulfillment API
#
# Provides linkage between the Observation and Fulfillment spaces within
# economic networks.
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type EconomicEvent {
  fulfills: [Fulfillment!]
}