##
#
# Observation <> ProcessSpecification indexes
#
# Extends Observation with the ability to refer to a specification for a Process
# that an Economic Resource may have gone through. This is known as "stage".
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type EconomicResource {
  "References the ProcessSpecification of the last process the desired economic resource went through. Stage is used when the last process is important for finding proper resources, such as where the publishing process wants only documents that have gone through the editing process."
  stage: ProcessSpecification
}

type ProcessSpecification {
  resourcesCurrentlyAtStage(first: Int, after: String, last: Int, before: String): EconomicResourceConnection
}
