##
#
# Observation <> Agreement API
#
# Augments EconomicEvent with properties that link events to Agreements
# which have governed the execution of those events.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type EconomicEvent {
  "This economic event occurs as part of this agreement."
  realizationOf: Agreement
}

type Agreement {
  economicEvents: [EconomicEvent!]
  unplannedEconomicEvents: [EconomicEvent!]
}

##
# API input and output types
##

input EconomicEventCreateParams {
  "(`Agreement`) This economic event occurs as part of this agreement."
  realizationOf: ID
}

input EconomicEventUpdateParams {
  "(`Agreement`) This economic event occurs as part of this agreement."
  realizationOf: ID
}
