input ProcessEventFilterParams {
  searchString: String
  providerId: [ID!]
  receiverId: [ID!]
  resourceClassifiedAs: [URI!]
  action: [ID!]
  startDate: DateTime
  endDate: DateTime
}

type Process {
  observedInputs(filter: ProcessEventFilterParams): [EconomicEvent!]
  observedOutputs(filter: ProcessEventFilterParams): [EconomicEvent!]
  unplannedInputs(filter: ProcessEventFilterParams): [EconomicEvent!]
  unplannedOutputs(filter: ProcessEventFilterParams): [EconomicEvent!]
}
