##
#
# Observation <> Geolocation API
#
# Augments records of real-world resources and observations with geospatial information.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type EconomicEvent {
  "The place where an economic event occurs.  Usually mappable."
  atLocation: SpatialThing

  "The new location of the receiver resource."
  toLocation: SpatialThing
}

type EconomicResource {
  "The current place an economic resource is located. Could be at any level of granularity, from a town to an address to a warehouse location. Usually mappable."
  currentLocation: SpatialThing
}

type SpatialThing {
  economicResources(first: Int, after: String, last: Int, before: String): EconomicResourceConnection
  economicEvents(first: Int, after: String, last: Int, before: String): EconomicEventConnection
}

input EconomicEventCreateParams {
  "(`SpatialThing`) The place where an economic event occurs.  Usually mappable."
  atLocation: ID

  "(`SpatialThing`) The new location of the receiver resource."
  toLocation: ID
}

input EconomicResourceCreateParams {
  "(`SpatialThing`) The current place an economic resource is located.  Could be at any level of granularity, from a town to an address to a warehouse location.  Usually mappable."
  currentLocation: ID
}
