##
#
# Observation <> Process API
#
# Augments Observation records (EconomicEvent specifically) with the ability to reference Processes
# and vice versa.
#
# @package  vf-graphql
# @since    2022-05-27
#
##

union TrackTraceItem = Process | EconomicResource | EconomicEvent
union ProductionFlowItem = Process | EconomicResource

type EconomicEvent {
  "Defines the process to which this event is an input."
  inputOf: Process

  "Defines the process for which this event is an output."
  outputOf: Process
}

type Process {
  ##############################################################################
  # inverse relationships and queries

  observedInputs: [EconomicEvent!]
  observedOutputs: [EconomicEvent!]
  unplannedInputs: [EconomicEvent!]
  unplannedOutputs: [EconomicEvent!]

  previous: [EconomicEvent!]
  next: [EconomicEvent!]
}

##
# API input and output types
##

input EconomicEventCreateParams {
  "(`Process`) Defines the process to which this event is an input."
  inputOf: ID

  "(`Process`) Defines the process for which this event is an output."
  outputOf: ID
}
