##
#
# Observation <> ResourceSpecification indexes
#
# Provides search intelligence for Observation module records via the
# ResourceSpecification module, enabling type-based queries.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type ResourceSpecification {
  conformingResources(first: Int, after: String, last: Int, before: String): EconomicResourceConnection
  economicEvents(first: Int, after: String, last: Int, before: String): EconomicEventConnection
}

type EconomicEvent {
  "The primary resource specification or definition of an existing or potential economic resource. A resource will have only one, as this specifies exactly what the resource is."
  resourceConformsTo: ResourceSpecification
}

type EconomicResource {
  "The primary resource specification or definition of an existing or potential economic resource. A resource will have only one, as this specifies exactly what the resource is."
  conformsTo: ResourceSpecification!
}

input EconomicEventCreateParams {
  "(`ResourceSpecification`) The primary resource specification or definition of an existing or potential economic resource. A resource will have only one, as this specifies exactly what the resource is."
  resourceConformsTo: ID
}

input EconomicResourceCreateParams {
  "(`ResourceSpecification`) The primary resource specification or definition of an existing or potential economic resource. A resource will have only one, as this specifies exactly what the resource is."
  conformsTo: ID
}
