##
#
# Process <> Commitment API
#
# Provides linkage between the Process and Commitment spaces within
# economic networks. The relationship is one-to-many from Process to Commitments
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type Commitment {
  "Defines the process to which this commitment is an input."
  inputOf: Process

  "Defines the process for which this commitment is an output."
  outputOf: Process
}

type Process {
  committedInputs: [Commitment!]
  committedOutputs: [Commitment!]
}

##
# API input and output types
##

input CommitmentCreateParams {
  "(`Process`) Defines the process to which this commitment is an input."
  inputOf: ID

  "(`Process`) Defines the process for which this commitment is an output."
  outputOf: ID
}

input CommitmentUpdateParams {
  "(`Process`) Defines the process to which this commitment is an input."
  inputOf: ID

  "(`Process`) Defines the process for which this commitment is an output."
  outputOf: ID
}
