input ProcessFilterParams {
  searchString: String
  finished: Boolean
  inScopeOf: [ID!]
  classifiedAs: [URI!]
  startDate: DateTime
  endDate: DateTime
}

type Query {
  processes(filter: ProcessFilterParams): ProcessConnection!
}
