##
#
# Process <> ProcessSpecification API
#
# Enables the classification of Processes using specifications for them
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type Process {
  "The definition or specification for a process."
  basedOn: ProcessSpecification
}

type ProcessSpecification {
  conformingProcesses(first: Int, after: String, last: Int, before: String): ProcessConnection
}

##
#  API call input and output types
##

input ProcessCreateParams {
  "(`ProcessSpecification`) The definition or specification for a process."
  basedOn: ID
}

input ProcessUpdateParams {
  "(`ProcessSpecification`) The definition or specification for a process."
  basedOn: ID
}
