input ProcessIntentFilterParams {
  searchString: String
  providerId: [ID!]
  receiverId: [ID!]
  resourceClassifiedAs: [URI!]
  action: [ID!]
  startDate: DateTime
  endDate: DateTime
}

type Process {
  intendedInputs(filter: ProcessIntentFilterParams): [Intent!]
  intendedOutputs(filter: ProcessIntentFilterParams): [Intent!]
}
