##
#
# Recipe <> ResourceSpecification API
#
# Extends Recipes with ResourceSpecification
#
# @package  vf-graphql
# @since    2022-05-27
#
##

type RecipeFlow {
  "The resource definition referenced by this flow in the recipe."
  resourceConformsTo: ResourceSpecification!
}

input RecipeFlowCreateParams {
  "(`ResourceSpecification`) The resource definition referenced by this flow in the recipe."
  resourceConformsTo: ID!
}

input RecipeFlowUpdateParams {
  "(`ResourceSpecification`) The resource definition referenced by this flow in the recipe."
  resourceConformsTo: ID
}
