##
#
# Action module
#
# Defines the available ways in which Economic Resources can be modified via Economic Events
# and the specifics of the effects of those.
# This is not dynamically extensible but rather comes as a pre-defined list, built in to the specification.
#
# @package  vf-graphql
# @since    2022-05-27
#
##

"""
An action verb defining the kind of event, commitment, or intent.
It is recommended that the lowercase action verb should be used as the record ID
in order that references to `Action`s elsewhere in the system are easily readable.
"""
type Action {
  id: ID!

  "A unique verb which defines the action."
  label: String!

  "The accounting effect of an economic event on a resource, increment, decrement, no effect, or decrement resource and increment 'to' resource."
  resourceEffect: String! # "increment", "decrement", "noEffect", "decrementIncrement"
  "The onhand effect of an economic event on a resource, increment, decrement, no effect, or decrement resource and increment 'to' resource."
  onhandEffect: String! # "increment", "decrement", "noEffect", "decrementIncrement"
  "Denotes if a process input or output, or not related to a process."
  inputOutput: String # "input", "output", "notApplicable"
  "The action that should be included on the other direction of the process, for example accept with modify."
  pairsWith: String # "notApplicable", (any of the action labels)
}

# Core VF action IDs & `resourceEffect`s:
# @see https://valueflo.ws/introduction/flows.html#actions

type Query {
  action(id: ID!): Action
  actions: [Action!]
}
