##
#
# Appreciation module
#
# Allows linking EconomicEvents to indicate that some contribution was given in loose appreciation for another.
#
# @depends  observation.gql
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A way to tie an economic event that is given in loose fulfilment for another economic event, without commitments or expectations.
Supports the gift economy.
"""
type Appreciation {
  id: ID!
  revisionId: ID!

  "The economic event this appreciation has been given in acknowledgement of."
  appreciationOf: EconomicEvent!

  "The economic event provided as a gift in this appreciation."
  appreciationWith: EconomicEvent!

  "The agent who is appreciating."
  appreciatedBy: Agent

  "A textual description or comment."
  note: String
}

##
# API input and output types
##

input AppreciationCreateParams {
  "(`EconomicEvent`) The economic event this appreciation has been given in acknowledgement of."
  appreciationOf: ID!

  "(`EconomicEvent`) The economic event provided as a gift in this appreciation."
  appreciationWith: ID!

  "(`Agent`) The agent who is appreciating."
  appreciatedBy: ID

  "A textual description or comment."
  note: String
}

input AppreciationUpdateParams {
  revisionId: ID!

  "(`EconomicEvent`) The economic event this appreciation has been given in acknowledgement of."
  appreciationOf: ID

  "(`EconomicEvent`) The economic event provided as a gift in this appreciation."
  appreciationWith: ID

  "A textual description or comment."
  note: String
}

type AppreciationResponse {
  appreciation: Appreciation!
}

type AppreciationConnection {
  edges: [AppreciationEdge!]!
  pageInfo: PageInfo!
}

type AppreciationEdge {
  node: Appreciation!
  cursor: String!
}

type Query {
  appreciation(id: ID!): Appreciation!
  appreciations(
    first: Int
    after: String
    last: Int
    before: String
  ): AppreciationConnection!
}

type Mutation {
  createAppreciation(
    appreciation: AppreciationCreateParams!
  ): AppreciationResponse!
  updateAppreciation(
    appreciation: AppreciationUpdateParams!
  ): AppreciationResponse!
  deleteAppreciation(revisionId: ID!): Boolean!
}
