##
#
# Entrypoint for connection query filtering schemas
#
# @see schemas/bridging/*.filtering.gql
#
# @package  ValueFlows GraphQL
# @since    2021-12-12
#
##

"Filtering module stub"
scalar _vf_filtering_dummy
