##
#
# Geolocation module
#
# Defines a generic data structure to represent a physical location
#
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A physical mappable location.
"""
type SpatialThing {
  id: ID!
  revisionId: ID!

  "An informal or formal textual identifier for a location. Does not imply uniqueness."
  name: String!

  "An address that will be recognized as mappable by mapping software."
  mappableAddress: String

  "Latitude."
  lat: Decimal

  "Longitude."
  long: Decimal

  "Altitude."
  alt: Decimal

  "A textual description or comment."
  note: String
}



input SpatialThingCreateParams {
  "An informal or formal textual identifier for a location. Does not imply uniqueness."
  name: String!

  "An address that will be recognized as mappable by mapping software."
  mappableAddress: String

  "Latitude."
  lat: Decimal

  "Longitude."
  long: Decimal

  "Altitude."
  alt: Decimal

  "A textual description or comment."
  note: String
}

input SpatialThingUpdateParams {
  revisionId: ID!

  "An informal or formal textual identifier for a location. Does not imply uniqueness."
  name: String

  "An address that will be recognized as mappable by mapping software."
  mappableAddress: String

  "Latitude."
  lat: Decimal

  "Longitude."
  long: Decimal

  "Altitude."
  alt: Decimal

  "A textual description or comment."
  note: String
}

type SpatialThingResponse {
  spatialThing: SpatialThing!
}


type SpatialThingConnection {
  edges: [SpatialThingEdge!]!
  pageInfo: PageInfo!
}

type SpatialThingEdge {
  node: SpatialThing!
  cursor: String!
}

type Query {
  spatialThing(id: ID!): SpatialThing
  spatialThings(first: Int, after: String, last: Int, before: String): SpatialThingConnection!
}

type Mutation {
  createSpatialThing(spatialThing: SpatialThingCreateParams!): SpatialThingResponse!
  updateSpatialThing(spatialThing: SpatialThingUpdateParams!): SpatialThingResponse!
  deleteSpatialThing(revisionId: ID!): Boolean!
}
