##
#
# Shared structs for connection result ordering parameters
#
# :TODO: revisit this to ensure we have a reliable cross-platform solution
#        when sending multiple ordering params (ie. 'SORT BY x ASC, y DESC')
#
# @see schemas/bridging/*.ordering.gql
#
# @package  ValueFlows GraphQL
# @since    2021-12-12
#
##

enum Sort {
  asc
  desc
}
