##
#
# Plan module
#
# Allows for grouping processes into related groups of work with defined deliverables.
#
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A logical collection of processes that constitute a body of planned work with defined deliverable(s).
"""
type Plan {
  id: ID!
  revisionId: ID!

  "An informal or formal textual identifier for a plan. Does not imply uniqueness."
  name: String!

  "The time the plan was made."
  created: DateTime

  "The time the plan is expected to be complete."
  due: DateTime

  "A textual description or comment."
  note: String

  "The plan is able to be deleted or not."
  deletable: Boolean
}

##
#  API call input and output types
##

input PlanCreateParams {
  "An informal or formal textual identifier for a plan. Does not imply uniqueness."
  name: String!

  "The time the plan was made."
  created: DateTime

  "The time the plan is expected to be complete."
  due: DateTime

  "A textual description or comment."
  note: String
}

input PlanUpdateParams {
  revisionId: ID!

  "An informal or formal textual identifier for a plan. Does not imply uniqueness."
  name: String

  "The time the plan was made."
  created: DateTime

  "The time the plan is expected to be complete."
  due: DateTime

  "A textual description or comment."
  note: String
}

type PlanResponse {
  plan: Plan!
}

type PlanConnection {
  edges: [PlanEdge!]!
  pageInfo: PageInfo!
}

type PlanEdge {
  node: Plan!
  cursor: String!
}

type Query {
  plan(id: ID!): Plan
  plans(first: Int, after: String, last: Int, before: String): PlanConnection!
}

type Mutation {
  createPlan(plan: PlanCreateParams!): PlanResponse!
  # :TODO:
  # createPlanFromRecipe(): PlanResponse!
  updatePlan(plan: PlanUpdateParams!): PlanResponse!
  deletePlan(revisionId: ID!): Boolean!
}
