##
#
# Recipe module
#
# Provides for creating shareable blueprints of potential workflows that can be
# deployed as work plans for undertaking the actual work.
#
# @depends  action.gql
# @depends  measurement.gql
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
The specification of a resource inflow to, or outflow from, a recipe process.
"""
type RecipeFlow {
  id: ID!
  revisionId: ID!

  "The amount and unit of the economic resource counted or inventoried."
  resourceQuantity: Measure

  "The amount and unit of the work or use or citation effort-based action. This is often a time duration, but also could be cycle counts or other measures of effort or usefulness."
  effortQuantity: Measure

  "Relates a process input or output to a verb, such as consume, produce, work, modify, etc."
  action: Action!

  "Relates an input flow to its process in a recipe."
  recipeInputOf: RecipeProcess

  "Relates an output flow to its process in a recipe."
  recipeOutputOf: RecipeProcess

  "Relates a flow to its exchange agreement in a recipe."
  recipeClauseOf: RecipeExchange

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization."
  resourceClassifiedAs: [URI!]

  "The state of the desired economic resource (pass or fail), after coming out of a test or review process."
  state: String

  "A textual description or comment."
  note: String
}

"""
Specifies a process in a recipe for use in planning from recipe.
"""
type RecipeProcess {
  id: ID!
  revisionId: ID!

  "An informal or formal textual identifier for a recipe process. Does not imply uniqueness."
  name: String!

  "The planned calendar duration of the process as defined for the recipe batch."
  hasDuration: Duration

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization."
  processClassifiedAs: [URI!]

  "Recipe process or definition that this process is based on."
  basedOn: RecipeProcess

  "A textual description or comment."
  note: String
}

"""
Specifies an exchange agreement as part of a recipe.
"""
type RecipeExchange {
  id: ID!
  revisionId: ID!

  "An informal or formal textual identifier for a recipe exchange. Does not imply uniqueness."
  name: String!

  "A textual description or comment."
  note: String
}

input RecipeProcessCreateParams {
  "An informal or formal textual identifier for a recipe process. Does not imply uniqueness."
  name: String!

  "The planned calendar duration of the process as defined for the recipe batch."
  hasDuration: IDuration

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization."
  processClassifiedAs: [URI!]

  "(`RecipeProcess`) Recipe process or definition that this process is based on."
  basedOn: ID

  "A textual description or comment."
  note: String
}

input RecipeProcessUpdateParams {
  revisionId: ID!

  "An informal or formal textual identifier for a recipe process. Does not imply uniqueness."
  name: String

  "The planned calendar duration of the process as defined for the recipe batch."
  hasDuration: IDuration

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization."
  processClassifiedAs: [URI!]

  "(`RecipeProcess`) Recipe process or definition that this process is based on."
  basedOn: ID

  "A textual description or comment."
  note: String
}

type RecipeProcessResponse {
  recipeProcess: RecipeProcess!
}

input RecipeExchangeCreateParams {
  "An informal or formal textual identifier for a recipe exchange. Does not imply uniqueness."
  name: String!

  "A textual description or comment."
  note: String
}

input RecipeExchangeUpdateParams {
  revisionId: ID!

  "An informal or formal textual identifier for a recipe exchange. Does not imply uniqueness."
  name: String

  "A textual description or comment."
  note: String
}

type RecipeExchangeResponse {
  recipeExchange: RecipeExchange!
}

input RecipeFlowCreateParams {
  "(`Action`) Relates a process input or output to a verb, such as consume, produce, work, modify, etc."
  action: ID!

  "The amount and unit of the economic resource counted or inventoried."
  resourceQuantity: IMeasure

  "The amount and unit of the work or use or citation effort-based action. This is often a time duration, but also could be cycle counts or other measures of effort or usefulness."
  effortQuantity: IMeasure

  "(`RecipeProcess`) Relates an input flow to its process in a recipe."
  recipeInputOf: ID

  "(`RecipeProcess`) Relates an output flow to its process in a recipe."
  recipeOutputOf: ID

  "(`RecipeExchange`) Relates a flow to its exchange agreement in a recipe."
  recipeClauseOf: ID

  "The state of the desired economic resource (pass or fail), after coming out of a test or review process."
  state: String

  "A textual description or comment."
  note: String
}

input RecipeFlowUpdateParams {
  revisionId: ID!

  "(`Action`) Relates a process input or output to a verb, such as consume, produce, work, modify, etc."
  action: ID

  "The amount and unit of the economic resource counted or inventoried."
  resourceQuantity: IMeasure

  "The amount and unit of the work or use or citation effort-based action. This is often a time duration, but also could be cycle counts or other measures of effort or usefulness."
  effortQuantity: IMeasure

  "(`RecipeProcess`) Relates an input flow to its process in a recipe."
  recipeInputOf: ID

  "(`RecipeProcess`) Relates an output flow to its process in a recipe."
  recipeOutputOf: ID

  "(`RecipeExchange`) Relates a flow to its exchange agreement in a recipe."
  recipeClauseOf: ID

  "The state of the desired economic resource (pass or fail), after coming out of a test or review process."
  state: String

  "A textual description or comment."
  note: String
}

type RecipeFlowResponse {
  recipeFlow: RecipeFlow!
}

type RecipeFlowConnection {
  edges: [RecipeFlowEdge!]!
  pageInfo: PageInfo!
}

type RecipeFlowEdge {
  node: RecipeFlow!
  cursor: String!
}

type RecipeProcessConnection {
  edges: [RecipeProcessEdge!]!
  pageInfo: PageInfo!
}

type RecipeProcessEdge {
  node: RecipeProcess!
  cursor: String!
}

type RecipeExchangeConnection {
  edges: [RecipeExchangeEdge!]!
  pageInfo: PageInfo!
}

type RecipeExchangeEdge {
  node: RecipeExchange!
  cursor: String!
}

type Query {
  recipeFlow(id: ID!): RecipeFlow
  recipeFlows(
    first: Int
    after: String
    last: Int
    before: String
  ): RecipeFlowConnection!

  recipeProcess(id: ID!): RecipeProcess
  recipeProcesses(
    first: Int
    after: String
    last: Int
    before: String
  ): RecipeProcessConnection!

  recipeExchange(id: ID!): RecipeExchange
  recipeExchanges(
    first: Int
    after: String
    last: Int
    before: String
  ): RecipeExchangeConnection!
}

type Mutation {
  createRecipeFlow(recipeFlow: RecipeFlowCreateParams!): RecipeFlowResponse!
  updateRecipeFlow(recipeFlow: RecipeFlowUpdateParams!): RecipeFlowResponse!
  deleteRecipeFlow(revisionId: ID!): Boolean!

  createRecipeProcess(
    recipeProcess: RecipeProcessCreateParams!
  ): RecipeProcessResponse!
  updateRecipeProcess(
    recipeProcess: RecipeProcessUpdateParams!
  ): RecipeProcessResponse!
  deleteRecipeProcess(revisionId: ID!): Boolean!

  createRecipeExchange(
    recipeExchange: RecipeExchangeCreateParams!
  ): RecipeExchangeResponse!
  updateRecipeExchange(
    recipeExchange: RecipeExchangeUpdateParams!
  ): RecipeExchangeResponse!
  deleteRecipeExchange(revisionId: ID!): Boolean!
}
